### ISSUE TITLE
demo not working after install

### ISSUE THREAD

**Issue by ghost** [NeuralEnsemble/MotionClouds#2]
Hi,
I'm assuming I've installed all the dependencies of - and MotionClouds. But when I run the first part of the demo I have the following error :
<img width="871" alt="screen shot 2015-10-20 at 23 23 28" src="https://cloud.githubusercontent.com/assets/15221042/10621960/54af082a-7784-11e5-8161-1f0978fe33c9.png">
Would you have an idea of what's happening ? I installed vispy 0.4.0 and all that is happening on Mac OS Yosemite, python 2.7 (anaconda distribution).

**Comment by laurentperrinet** [comment]
thanks for the detailed report!

what is happening is that I have updated the code to use the latest version of `vispy` which does a better job at displaying envelopes - and that this breaks the compatibility to older code. 

best would be to update to the latest version of `vispy` from the github repo, for instance with this command:

```
pip install git+https://github.com/vispy/vispy.git
```

not sure how you do that in anaconda...
