### ISSUE TITLE
Problems with creating videos

### ISSUE THREAD

**Issue by ChrisWiesbrock** [NeuralEnsemble/MotionClouds#3]
Hey,

I copied parts of the example "Testing grating" into a new file.  This is my script:

> import numpy as np
> np.set_printoptions(precision=3, suppress=True)
> import pylab
> import matplotlib.pyplot as plt
> 
> from MotionClouds import MotionClouds as mc
> import os
> fx, fy, ft = mc.get_grids(mc.N_X, mc.N_Y, mc.N_frame)
> print(mc.envelope_orientation.**doc**)
> 
> name = 'grating'
> # initialize
> 
> fx, fy, ft = mc.get_grids(mc.N_X, mc.N_Y, mc.N_frame)
> color = mc.envelope_color(fx, fy, ft)
> 
> z = color \* mc.envelope_gabor(fx, fy, ft)
> mc.figures(z, name)
> mc.in_show_video(name)

It runs fine until the last line. I get following error message:

> runfile('C:/Users/Chris/Documents/Python Scripts/untitled13.py', wdir='C:/Users/Chris/Documents/Python Scripts')
> 
> Saving sequence results/grating.mp4
> grating
> Traceback (most recent call last):
> 
>   File "<ipython-input-3-e12b3e7cf319>", line 1, in <module>
>     runfile('C:/Users/Chris/Documents/Python Scripts/untitled13.py', wdir='C:/Users/Chris/Documents/Python Scripts')
> 
>   File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/Chris/Documents/Python Scripts/untitled13.py", line 24, in <module>
>     mc.in_show_video(name)
> 
>   File "C:\Python27\lib\site-packages\MotionClouds\MotionClouds.py", line 644, in in_show_video
>     video = open(os.path.join(figpath, name + vext), "rb").read()
> 
> IOError: [Errno 2] No such file or directory: 'results/grating.mp4'

The figures of the cubes are saved correctly into the figures folder, but somehow my system fails to create/save the videofile. It is also not working correctly when I try to save the frames into a zip-file. I use Spyder with Python(x.y) 2.7.10.0, which should include all needed packages. I run it on Windows 8.1 (64 bit). I tried the same script on a mashine with Ubuntu 16.04 but I had the same error message. 

With best regards and many thanks in advance!
Christopher Wiesbrock

**Comment by laurentperrinet** [comment]
hey @ChrisWiesbrock and thanks a lot for your detailed report! it is very helpful to debug your specific problem and also for me as I never had the chance to test it on windows (sigh)... 

first of all, you seem to use a sequence used mainly to show such clouds in an `ipython` notebook - this will still work in `spyder` but you could use this simpler minimal working example showing a similar diagnosis (you cannot save the video file):

```
import MotionClouds as mc
fx, fy, ft = mc.get_grids(mc.N_X, mc.N_Y, mc.N_frame)
envelope = mc.envelope_gabor(fx, fy, ft)
movie = mc.random_cloud(envelope)
mc.anim_save(mc.rectif(movie), '/tmp/hello', vext='.mp4') 
```

to me, it seems the obvious happened:  you do not have in your path a binary called `ffmpeg`  that points to the [Swiss army knife for video editing](http://ffmpeg.org/)... two solutions : either you manage to get `ffmpeg` running, or you save to a less demanding format, such as `.png`, which saves the movie as a sequence of PNG graphic files (lossless). The latter is often enough to preview how frames look like qualitatively and also to be loaded in any experimental box (such as psychotoolbox). Another format is directly in binary, either `.npy` for numpy of `.mat` for MATLAB®.

Hope it helps!
